# Site
name: "Financiën enzo"
title: "Financiën enzo - investeer in je toekomst"
description: "Jekyll Theme for Blogging"
meta_description: "Jekyll theme for blogging."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: '/'
email: ''
google_analytics: ''
disqus: ''
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  financien:
    name: Financien
    display_name: Financiën enzo
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    web: https://financienenzo.nl
    description: "De eigenaar van dit blog."
 Sandra:
    name: Sandra
    display_name: Ik ben Jan Modaal
    web: https://ikbenjanmodaal.nl
    description: "Sandra is blogger op ikbenjanmodaal.nl en heeft de Money Game ontwikkeld"
  
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-redirect-from
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    post: '/:title/'
    
# Other
permalink: /:title/
markdown: kramdown
highlighter: rouge
search: true
timezone: Europe/Amsterdam
lang: nl-nl
