# Site
name: "Financiën enzo"
title: "Financiën enzo - investeer in je financiële toekomst"
description: "Financiën enzo is een persoonlijk blog welke tips en trucks geeft om te investeren in je financiële toekomst."
meta_description: "Financiën enzo is een persoonlijk blog welke tips en trucks geeft om te investeren in je financiële toekomst. Het is blijft belangrijk om zelf onderzoek uit te voeren naar de tips en trucks welke je hier tegen komt. Dit blog geeft géén persoonlijk financieel advies!"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 8
baseurl: '/'
email: 'financienenzo@gmail.com'
google_analytics: 'UA-6202229-31'
disqus: 'financienenzo'
sharethis: '<script type="text/javascript" src="https://platform-api.sharethis.com/js/sharethis.js#property=604771394d1bac0012adedb1&product=sticky-share-buttons" async="async""></script>'
# Authors
authors:
  Financien:
    name: Financien
    display_name: "Financiën enzo"
    gravatar: 5c9a960a12c19be7f73301903c50a6eb
    web: https://financienenzo.nl
    description: "Wij zijn financiën enzo. Wij delen welke stappen wij hebben ondernomen om meer inzicht te krijgen in onze financiën en op welke manieren wij investeren in onze financiële toekomst."
  Sandra:
    name: Sandra
    display_name: "Ik ben Jan Modaal"
    web: https://www.paypro.nl/producten/Ik_ben_Jan_Modaal/79165/86238
    description: "Sandra is blogger op ikbenjanmodaal.nl en heeft de Money Game ontwikkeld"
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-redirect-from
  - jekyll-target-blank

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
 
# Other
permalinks:
  post: '/:categories/:title'
markdown: kramdown
highlighter: rouge
timezone: Europe/Amsterdam
lang: nl-nl
